trigger:
  - main

pool:
  name: RecursiveDevAgent

stages:
  - stage: DeploySonarQube
    displayName: "Deploy SonarQube"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: TerraformUpResources
        displayName: "Deploy Terraform resources into AWS"
        condition: succeeded()
        steps:
          - template: "azure-templates/Build-Resource.yml"

      - job: waitForValidation
        displayName: "Wait for external validation"
        dependsOn: TerraformUpResources
        condition: succeeded()
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
            notifyUsers: |
              example@example.com
            instructions: 'If you want to take down your resources, click on resume'
            onTimeout: 'reject'

      - job: TerraformDownResources
        displayName: "Destroy Terraform resources deployed to AWS"
        dependsOn:
          - waitForValidation
          - TerraformUpResources
        condition: or
          (
            eq(dependencies.waitForValidation.result, 'Succeeded'),
            eq(dependencies.TerraformUpResources.result, 'failed')
          )
        steps:
          - template: "azure-templates/Destroy-Resource.yml"
